---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - shared-configmap.yaml
namespace: simulator-spi
replicas:
  - name: simulator-spi
    count: 1
images:
  - name: ghcr.io/lb-conn/simulator-spi/spi
    newTag: "latest"
patches:
  - target:
      kind: Deployment
      name: simulator-spi
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/qa.londonbridge.service
        value: simulator-spi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 300Mi
  - target:
      kind: Service
      name: simulator-spi
    patch: |-
      - op: add
        path: /spec/selector/qa.londonbridge.service
        value: simulator-spi
