---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - simulator-spi-deployment.yaml
  - simulator-spi-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: simulator-spi
